runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /Styles
  static_dir: css
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
